config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: 'main#index'
  resources :entries, only: [:create, :new, :destroy]

  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"

  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"

  get "entries", to: "entries#index"
  post "entries", to: "entries#create"

  get "new_entries", to: "entries#new"
  post "new_entries", to: "entries#create"

  delete "logout", to: "sessions#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
end

app/models/entry.rb
class Entry < ApplicationRecord
    belongs_to :user
    has_one_attached :image
end

app/models/user.rb
# email:string 
# password_digest:string
#
# password:string virtual attribute
# password_confirmation: string virtual attribute

class User < ApplicationRecord
    has_secure_password

    validates :email, presence: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: "must be a valid email address" }

    has_many :entries
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_current_user
    
    def set_current_user
        if session[:user_id]
            Current.user = User.find_by(id: session[:user_id])
        end
    end


    private

    def require_login
        unless logged_in?
        flash[:alert] = 'You must be logged in to access this page.'
        redirect_to sign_in_path
        end
    end

    def logged_in?
        session[:user_id].present?
    end

    helper_method :logged_in?

    helper_method :current_user 
    private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
    #before_action :authenticate_user! # Ensures the user is logged in before accessing the actions
  
    before_action :require_login

    def new
        @entry = Entry.new
    end
    
    def index
        @entries = current_user.entries
    end

    def create
      @entry = current_user.entries.build(entry_params)
  
      if @entry.save
        redirect_to entries_path, notice: 'Entry was successfully created.'
      else
        render :new
      end
    end

    private
    def entry_params
        params.require(:entry).permit(:title, :content, :image)
    end

    def show
      @entry = Entry.find(params[:id]) # Assuming you have a find method to retrieve the entry by its ID
    end
  

  end

app/controllers/main_controller.rb
class MainController < ApplicationController
    def index
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
    def new
        # instant variable as in ruby the variable would only be inside of this method
        # instant variables available in our views
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to root_path, notice: "Successfully created account"
        else
            render :new 
        end
    end

    private
    def user_params
        params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end

    def create
        user = User.find_by(email: params[:email])

        if user.present? && user.authenticate(params[:password])
            session[:user_id] = user.id
            redirect_to root_path, notice: "Logged in successfully"
        else
            flash[:alert] = "Invalid email or password"
            render :new 
        end
    end

    def destroy 
        session[:user_id] = nil
        redirect_to root_path, notice: "Logged out"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/index.html.erb
<body>
  <div class="container mt-4">
    <div class="row row-cols-3 g-4">
      <% if @entries.present? %>
        <% @entries.each do |entry| %>
          <div class="col">
            <div class="card h-100">
              <% if entry.image.attached? %>
                <%= image_tag entry.image, class: "card-img-top img-fluid" %>
              <% else %>
                <div class="bg-secondary text-light text-center py-5">
                </div>
              <% end %>
              <div class="card-body">
                <h5 class="card-title"><%= entry.title %></h5>
                <p class="card-text"><%= entry.content %></p>
              </div>
            </div>
          </div>
        <% end %>
      <% else %>
        <div class="col text-center">
          <p>No entries found.</p>
        </div>
      <% end %>
    </div>

    <div class="text-center mt-4">
      <a class="btn btn-lg btn-secondary" href="entries/new" role="button">New Entry</a>
    </div>
  </div>
</body>

app/views/entries/new.html.erb
<body>

  <div class="cover-container d-flex h-100 p-3 mx-auto flex-column">
    <div class="container narrow-form-container">
        <h1>Add a new entry</h1>
    <%= form_with model: @entry, url: entries_path, data: { turbo: false } do |form| %>

    <div class="mb-3">
        <%= form.label :title %>
        <%= form.text_field :title, class: "form-control", placeholder: "Title" %>
    </div>
    <div class="mb-3">
        <%= form.label :content %>
        <%= form.text_field :content, class: "form-control", placeholder: "Description" %>
    </div>
    <div>
  <%= form.label :image %>
  <div class="d-flex align-items-center mb-2">
    <label for="file-upload" class="btn btn-lg btn-secondary">
      Choose File
    </label>
    <%= form.file_field :image, id: "file-upload", class: "form-control mb-0 ms-2 visually-hidden" %>
  </div>
</div>
    <div class="mb-3">
        <%= form.submit "Submit Entry", class: "btn btn-lg btn-secondary" %>
    </div>

    <% end %>
    </div>
  </div>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
 <head>
   <title>Journal</title>
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <%= csrf_meta_tags %>
   <%= csp_meta_tag %>

   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
   <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
   <%= javascript_importmap_tags %>
 </head>

  <body>
    
    <div>
      <%= render '/shared/navbar' %>
    </div>

    <div class="container">
      <%= render partial: "shared/flash" %>
      <%= yield %>
    </div>


      <%= render 'shared/footer' %>

  </body>
</html>

app/views/main/index.html.erb
<body class="text-center">

    <div class="cover-container d-flex h-100 p-3 mx-auto flex-column">
      

      <main role="main" class="inner cover">
        <h1 class="cover-heading">Welcome to JourneyMemoir</h1>
        <p class="lead">Relive, Recommend, and Roam Again!</p>
        <% if !Current.user %>
        <p class="lead">
          <a href="/sign_up" class="btn btn-lg btn-secondary">Sign up</a>
          <a href="/sign_in" class="btn btn-lg btn-secondary">Sign in</a>
        </p>
        <% end %>
      </main>

    
    </div>

</body>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
    <div class="alert alert-info mt-4" role="alert">
        <%= flash[:notice] %>
    </div>
<% end %>

<% if flash[:alert] %>
    <div class="alert alert-warning mt-4" role="alert">
        <%= flash[:alert] %>
    </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="d-flex flex-wrap justify-content-between align-items-center py-3 mt-4 border-top">
    <p class="footer-text col-md-4 mb-0 text-muted">© 2023 Company, Inc</p>
    
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <%= link_to "JourneyMemoir", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if Current.user %>
          <li class="nav-item">
            <%= link_to "My Entries", entries_path , class: "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "New Entry", new_entry_path , class: "nav-link"%>
          </li>
        <% else %>
          <!-- Add any other links for non-logged-in users -->
        <% end %>
      </ul>
      <ul class="navbar-nav">
        <% if Current.user %>
          <li class="nav-item">
            <div class="d-flex align-items-center">
              <span class="navbar-text me-2"><%= Current.user.email %></span>
            </div>
          </li>
          <li class="nav-item">
            <%= button_to "Logout", logout_path, method: :delete, class: "btn btn-lg btn-secondary nav-link text-white" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", sign_in_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Up", sign_up_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>